FROM docker.io/moodlehq/moodle-php-apache:8.2

USER root

# Install Composer from the official installer.
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
	&& php composer-setup.php --install-dir=/usr/local/bin --filename=composer \
	&& php -r "unlink('composer-setup.php');"

# Required for session.save_handler=redis.
#RUN pecl install redis \
#	&& docker-php-ext-enable redis
